simulation:
  dt: 0.05
  total_time: 120.0

approach:
  glideslope_deg: 3.3
  h_threshold: 15.0
  x_threshold: 0.0
  x_window: 2000.0
  h_ground: 1.0

limits:
  phi_deg_max: 40

guidance_gains:
  tau_heading: 0.7

initial_state:
  x: -6000.0
  y: 800.0
  h: 350.0
  V: 72.0
  psi_deg: 0.0
  gamma_deg: -3.0
  phi_deg: 0.0
  throttle: 0.6
  n: 1.0

references:
  V_ref: 72.0

guidance_gains:
  K_y_P: 0.012
  K_y_D: 1.6
  tau_heading: 1.2

  K_h_P: 0.012
  K_h_D: 0.030
  tau_gamma: 1.0

  K_V_P: 0.05

limits:
  phi_deg_max: 40
  tau_heading: 0.7
  phi_rate_deg_s: 20.0
  gamma_deg_min: -12.0
  gamma_deg_max: 3.0
  n_min: 0.7
  n_max: 2.5
  n_rate: 2.0

aircraft:
  mass: 6500.0
  S: 30.0
  rho: 1.225
  CD0: 0.03
  k: 0.05
  Tmax: 25000.0
  throttle_min: 0.05
  throttle_max: 1.0

wind: {}

metrics:
  gate_h_m: 300.0
  touchdown_x_window_m: 150.0

